# Generated by Django 2.2.2 on 2019-07-04 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sub_heading_one', models.CharField(blank=True, max_length=200, null=True)),
                ('body_one', models.TextField(blank=True, null=True)),
                ('img_one', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('body_two', models.TextField(blank=True, null=True)),
                ('sub_heading_two', models.CharField(blank=True, max_length=200, null=True)),
                ('body_three', models.TextField(blank=True, null=True)),
                ('img_two', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('body_four', models.TextField(blank=True, null=True)),
                ('sub_heading_three', models.CharField(blank=True, max_length=200, null=True)),
                ('body_five', models.TextField(blank=True, null=True)),
                ('img_three', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('body_six', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Comment_owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'comment_owner',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('comment_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment_owner')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
