# Generated by Django 2.2.2 on 2019-07-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190705_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='code_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='code_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
