# Generated by Django 2.2.2 on 2019-07-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190705_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sub_heading_one',
            new_name='sub_heading_1',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sub_heading_three',
            new_name='sub_heading_2',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sub_heading_two',
            new_name='sub_heading_3',
        ),
        migrations.AddField(
            model_name='article',
            name='sub_heading_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_heading_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_heading_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
